local monarch = require "monarch.monarch"

function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })

	

	msg.post(".", "ready")
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		print("Touch!")
	end

	
end

function on_message(self, message_id, message, sender)

	if message_id == hash("ready") then
		print("ready")
		monarch.show(hash("energy_ball"))

	end


end

